### ISSUE TITLE
elasticDSN does not allow HTTPS URLs

### ISSUE THREAD

**Issue by SchumacherFM** [zarplata/zabbix-agent-extension-elasticsearch#13]
Hi there,

thank you for this tool but we actually can't use it because the HTTP protocol has been hardcoded. For example here: https://github.com/zarplata/zabbix-agent-extension-elasticsearch/blob/master/elastic.go#L203

Our services run on HTTPS and that does not work :-(

Can you please fix it?

Thanks!

**Comment by tears-of-noobs** [comment]
@SchumacherFM Hi. Try out `https` branch.

**Comment by SchumacherFM** [comment]
Works for me! Thanks!
