### ISSUE TITLE
Unsupported item key -discover rules

### ISSUE THREAD

**Issue by ggggsc** [zarplata/zabbix-agent-extension-elasticsearch#14]
my es version: 6.6.5
my zabbix version: 4.0.4

deployed follow the instruction,but the discovery rule doesn't work.
 I'm sure that there's no x-pack active, no user&password needed
How can i deal with this?
![微信截图_20190317133959](https://user-images.githubusercontent.com/47072644/54485804-75dc4e80-48ba-11e9-8c53-852e50643f62.png)
![微信截图_20190317134117](https://user-images.githubusercontent.com/47072644/54485806-7e348980-48ba-11e9-9b0d-5a606aa71832.png)

**Comment by tears-of-noobs** [comment]
@ggggsc Hi. Did you restart `zabbix-agent` after the extension was installed? `Unsupported item key` is a result in two problems:

- `zabbix-agent` didn't restart after installation
- misconfiguration of `zabbix-agent` when it doesn't know about new items installed by https://github.com/zarplata/zabbix-agent-extension-elasticsearch/blob/master/zabbix-agent-extension-elasticsearch.conf. Check the config of `zabbix-agent` and be shure that config contains `Include` parameter and this include path contains file `zabbix-agent-extension-elasticsearch.conf`
