### ISSUE TITLE
make fails with zabbix-agent-extension-elasticsearch is not within a known GOPATH/src

### ISSUE THREAD

**Issue by rugenl** [zarplata/zabbix-agent-extension-elasticsearch#20]
"make" fails on Fedora system

$ make
Clean dependencies
rm -rf vendor/*
Clean builded binaries
rm -rf .out/
Done
Fetch dependencies
dep ensure -v
/home/me/zabbix-agent-extension-elasticsearch is not within a known GOPATH/src
make: *** [Makefile:37: deps] Error 1

**Comment by tears-of-noobs** [comment]
@rugenl Hi. I've made fixes to build rules. Try out again, please.

**Comment by rugenl** [comment]
Fixed, thanks.
