### ISSUE TITLE
Debugging tip

### ISSUE THREAD

**Issue by rugenl** [zarplata/zabbix-agent-extension-elasticsearch#21]
If you're having problems with the parameters sent, a debugging trick is to add echo here:
UserParameter=elasticsearch.stats[*], echo /usr/bin/zabbix-agent-extension-elasticsearch....

The zabbix item returned is then what you would try to pass to the command.

I didn't know where to comment other than make an issue.

**Comment by tears-of-noobs** [comment]
@rugenl Right way to help - make a PR, for example - paragraph with your solution in README.md.
