### ISSUE TITLE
Roles or permissions needed for zabbix monitoring user in elasticsearch

### ISSUE THREAD

**Issue by rugenl** [zarplata/zabbix-agent-extension-elasticsearch#22]
I think I have the elastic stats parts working, the index stats is failing due to elastic security, the user doesn't have rights to "IndicesStatsRequest".  

Any idea what role or access I need to add to my monitoring user?

Thansk

**Comment by tears-of-noobs** [comment]
@rugenl It's not an issue of the extension. Check out official Elasticsearch documentation to solve your problem.
