### ISSUE TITLE
Error when manual build!

### ISSUE THREAD

**Issue by chithanh89** [zarplata/zabbix-agent-extension-elasticsearch#24]
HI,

I get an error when manual build,
Clean dependencies
rm -rf vendor/*
Clean builded binaries
rm -rf .out/
rm -rf .gopath/
Done
Creating GOPATH
mkdir -p .gopath/src
ln -s /root/zabbix-agent-extension-elasticsearch /root/zabbix-agent-extension-elasticsearch/.gopath/src/zabbix-agent-extension-elasticsearch
Fetch dependencies
cd /root/zabbix-agent-extension-elasticsearch/.gopath/src/zabbix-agent-extension-elasticsearch; \
	GOPATH=/root/zabbix-agent-extension-elasticsearch/.gopath \
	dep ensure -v
/bin/sh: 2: dep: not found
Makefile:40: recipe for target 'deps' failed
make: *** [deps] Error 127
How can resolve this error? Plz help me.
Tks so much

**Comment by tears-of-noobs** [comment]
Hi @chithanh89. You should install `dep` on your build machine

**Comment by chithanh89** [comment]
@tears-of-noobs How to install dep? I am newbie and that's good when u give me clear instruction.
Tks so much bro.

**Comment by tears-of-noobs** [comment]
@chithanh89 https://golang.github.io/dep/docs/installation.html

**Comment by tears-of-noobs** [comment]
@chithanh89 Also you can try the `go-modules` branch which not require the `dep` but you should have `golang` version >= 1.11

**Comment by chithanh89** [comment]
@tears-of-noobs tks so much, i have build succesful after installed go dep.Have a nice day,bro!
