### ISSUE TITLE
How to configure in zabbix-agent-extension-elasticsearch.conf file and make it work?

### ISSUE THREAD

**Issue by Maning8** [zarplata/zabbix-agent-extension-elasticsearch#3]
Hi, 
I am facing some issue for extension configuration. Can anyone help to figure out how to make it work?

Zabbix-agent version: 3.4.11
**My configuration like below:**
es-01:/usr/local/zabbix/etc/zabbix_agentd.conf.d # cat zabbix-agent-extension-elasticsearch.conf
UserParameter=elasticsearch.discovery[*], /usr/bin/zabbix-agent-extension-elasticsearch --discovery --agg-group $1
UserParameter=elasticsearch.stats[*], /usr/bin/zabbix-agent-extension-elasticsearch --zabbix-host $1 --zabbix-prefix $2
UserParameter=elasticsearch.indices.discovery[*], /usr/bin/zabbix-agent-extension-elasticsearch indices --discovery --agg-group $1
UserParameter=elasticsearch.indices.stats[*], /usr/bin/zabbix-agent-extension-elasticsearch indices --zabbix-host $1 --zabbix-prefix $2 --agg-group $3
elasticsearch.stats[{$ZABBIX_SERVER_IP},{$ES_ZBX_PREFIX},ESIP:ESPORT]

**This is my zabbix-agentd configuration:**
LogFile=/tmp/zabbix_agentd.log
Server=$zabbix_server_ip
ServerActive=$zabbix_server_ip:10051
Hostname=es-01
Include=/usr/local/zabbix/etc/zabbix_agentd.conf.d/

The Macros for one node in cluster:
![host_macro](https://user-images.githubusercontent.com/25873573/42267005-77003ef4-7faa-11e8-9331-5b5fde40543f.png)

The Macros for Elastic Template:
![inkedtemplate_macro](https://user-images.githubusercontent.com/25873573/42267087-ad5ad63a-7faa-11e8-90b1-1f53766654a5.jpg)

Hope someone can elaborate on the specific configuration steps and the set of key parameters. If my statement is not clear enough, please point out.  thanks in advance!

**Comment by tears-of-noobs** [comment]
@Maning8 Hi. Can you show me what you see in `Latest data` of your server? I'm interested with `Elasticsearch get stats` item if everything is ok it must show - `OK` value. And you didn't say about what concretely doesn't work :)

**Comment by Maning8** [comment]
@tears-of-noobs Thanks for your reply! Sure. There is `Latest data` of my Zabbix server
`Last check` and `Last value` are empty
![elasticsearch_latest_data](https://user-images.githubusercontent.com/25873573/42297385-ad478616-8031-11e8-84ab-5c4ceb984ee3.png)

![elasticsearch_jvm](https://user-images.githubusercontent.com/25873573/42297395-b444921a-8031-11e8-9dde-635dbd10a92b.png)

**Comment by tears-of-noobs** [comment]
@Maning8 Hmmm, try to remove this string - `elasticsearch.stats[{$ZABBIX_SERVER_IP},{$ES_ZBX_PREFIX},ESIP:ESPORT]` from your config and then restart zabbix-agentd.

Zabbix agent  configuration for Elasicsearch must look like this 
```
UserParameter=elasticsearch.discovery[*], /usr/bin/zabbix-agent-extension-elasticsearch --discovery --agg-group $1
UserParameter=elasticsearch.stats[*], /usr/bin/zabbix-agent-extension-elasticsearch --zabbix-host $1 --zabbix-prefix $2
#
UserParameter=elasticsearch.indices.discovery[*], /usr/bin/zabbix-agent-extension-elasticsearch indices --discovery --agg-group $1
UserParameter=elasticsearch.indices.stats[*], /usr/bin/zabbix-agent-extension-elasticsearch indices --zabbix-host $1 --zabbix-prefix $2 --agg-group $3
```

**Comment by Maning8** [comment]
@tears-of-noobs Yeah, I commented the last line that I added before. but it showed the below error:
![zabbix-agent-extension-configure-and-start-error](https://user-images.githubusercontent.com/25873573/42301925-9cfa6990-804a-11e8-9fca-9ea5c7acbab3.png)

**Comment by tears-of-noobs** [comment]
@Maning8 This error means that you already have this `UserParameter` key - `elasticsearch.discovery`. Perhaps you have another configuration file that also included by zabbix-agentd. Do `grep -r 'elasticsearch.discovery' /usr/local/zabbix/etc/zabbix_agentd.conf.d/` to find in what other configuration file contains this `UserParameter`

**Comment by Maning8** [comment]
@tears-of-noobs Yes, this is it. I backuped the `zabbix-agent-extension-elasticsearch.conf` as `zabbix-agent-extension-elasticsearch.conf.bak`  under the `/usr/local/zabbix/etc/zabbix_agentd.conf.d/` folder. So when I start `zabbix-agent` got the above error.


Now I success start zabbix_agent, but the `Latest data` was still empty.
For `Elasticsearch get stats` item, there is  `Usage: zabbix-agent-extension-elastic ` like this:
![elasticsearch-get-stats](https://user-images.githubusercontent.com/25873573/42310058-02e1e0d6-806d-11e8-9ce5-e6bb54a83ca0.png)
And the JVM items are still no data.
![elasticsearch-zabbix-jvm](https://user-images.githubusercontent.com/25873573/42310099-1f67a948-806d-11e8-9c8e-344f4a1efa58.png)

I check the usage for the `zabbix-agent-extension-elasticsearch`,  but I don't quite understand how to use it. Do you need other information to investigate?

**Comment by tears-of-noobs** [comment]
@Maning8 I make some fixes in `https://github.com/zarplata/zabbix-agent-extension-elasticsearch/blob/master/zabbix-agent-extension-elasticsearch.conf`. Use new configuration and report me if errors still remain.

**Comment by Maning8** [comment]
@tears-of-noobs Thanks! Now I am using the new configuration file. `Elasticsearch get stats` history shows this:
![elasticsearch-get-stats-history](https://user-images.githubusercontent.com/25873573/42313023-4e64aafa-8074-11e8-9241-c53ae75f2679.png)

**Comment by tears-of-noobs** [comment]
@Maning8 What version of the Elasticsearch do you use? If you use X-pack maybe you must open access from your Zabbix server to your Elasticsearch cluster https://www.elastic.co/guide/en/x-pack/current/ip-filtering.html.

**Comment by Maning8** [comment]
@tears-of-noobs I'm using Elasticsearch-6.2.4. There was no `X-pack` configuration in my `elasticsearch.yml`. According to links you gave I add `X-pack` line in `elasticsearch.yml` and restart the elasticsearch:
`xpack.security.transport.filter.allow: [ "172.21.0.0/24","127.0.0.1" ]`

the `Elasticsearch get stats` show :
![20180705174737](https://user-images.githubusercontent.com/25873573/42316123-9a961f9c-807b-11e8-9a57-b5b2ddcf7589.png)


I can use `curl` command to get cluster information on the local server.
es-02:~ # curl -u elastic -XGET http://127.0.0.1:9200/_cluster/health
Enter host password for user 'elastic':
{"cluster_name":"es6-cluster","status":"green","timed_out":false,"number_of_nodes":3,"number_of_data_nodes":3,"active_primary_shards":35,"active_shards":71,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}

In this way, I used the account `elastic` to get cluster info? how should I  configure it in zabbix configuration?

**Comment by tears-of-noobs** [comment]
@Maning8 Currently extension doesn't support authentication into Elasticsearch cluster. His work assumes that there is anonymous access. For now I advice setup an anonymous user for access to API. How to do this written here - `https://www.elastic.co/guide/en/x-pack/6.2/anonymous-access.html` About available roles - `https://www.elastic.co/guide/en/x-pack/current/built-in-roles.html`.  I will try to add functionality for user authorization in nearest future.

**Comment by Maning8** [comment]
@tears-of-noobs OK! Thanks for your help! I will refer to the links you gave.

**Comment by Maning8** [comment]
@tears-of-noobs I sincerely appreciate your help! It works. You can close this issue.

**Comment by Maning8** [comment]
@tears-of-noobs Hi, The data for `Elasticsearch get indices stats`. this shoud be `OK`, right? 
![20180706170028](https://user-images.githubusercontent.com/25873573/42369993-2f0fc796-813e-11e8-8092-993f298a0d2e.png)

**Comment by tears-of-noobs** [comment]
@Maning8 I have made one more fixes in `https://github.com/zarplata/zabbix-agent-extension-elasticsearch/blob/master/zabbix-agent-extension-elasticsearch.conf` Try to use this new configuration.

**Comment by tsykl2008** [comment]
> @ tear-of-noobs嗨，数据为`Elasticsearch get indices stats`。这应该是吧`OK`，对吗？
> ![20180706170028](https://user-images.githubusercontent.com/25873573/42369993-2f0fc796-813e-11e8-8092-993f298a0d2e.png)

怎么处理的，我的好像也是跟你一样的问题，你是怎么处理的

**Comment by tsykl2008** [comment]
> @ Maning8我在`https://github.com/zarplata/zabbix-agent-extension-elasticsearch/blob/master/zabbix-agent-extension-elasticsearch.conf`Try尝试使用这个新配置时又做了一个修复。
![image](https://user-images.githubusercontent.com/22772930/64943090-648df200-d89d-11e9-82f7-6d47f99dcbce.png



> @ Maning8我在`https://github.com/zarplata/zabbix-agent-extension-elasticsearch/blob/master/zabbix-agent-extension-elasticsearch.conf`Try尝试使用这个新配置时又做了一个修复。

![1](https://user-images.githubusercontent.com/22772930/64943119-7a031c00-d89d-11e9-8d1d-62adcd8e86a8.png)
你好，我的出现这种情况，好像有些数据出来了，但是很多都没有出来数据，见图，请问是什么原因呢
