### ISSUE TITLE
Some documentations precisions

### ISSUE THREAD

**Issue by julienmary** [zarplata/zabbix-agent-extension-elasticsearch#30]
1. Is is necessary to have zabbix sender installed ? The zabbix documentation mentions that the use of trapper requires zabbix sender.

2. A macro need to be defined with {$ZABBIX_SERVER_IP} in global or local (template) scope with IP address of zabbix server. What if a zabbix proxy sits in the middle ?

**Comment by tears-of-noobs** [comment]
@julienmary 1) No, the `zabbix_sender` not required cuz the extension implements `zabbix_sender` protocol. 2) I suggest making the macro in the global scope where you host has been created. According to trapper items mechanics, you should assign to `ZABBIX_SERVER_IP` that IP address where your host with items located.
