### ISSUE TITLE
What is meant by {$GROUPNAME} = REAL_GROUP_NAME?

### ISSUE THREAD

**Issue by LandonStewart** [zarplata/zabbix-agent-extension-elasticsearch#5]
Does this mean if I have hosts belonging to a Zabbix group called "Production ES" I should define {$GROUPNAME} as "Production ES"?

**Comment by tears-of-noobs** [comment]
No, you must define a separate group, like - "elasticsearch_aggregation" it needs only on "master" nodes. For example:

- You have 3 master node (node1, node2, node3)
- You must create a special group for value aggregation (elasticsearch_aggregate)
- You must put your three nodes into this group
- You must define the macro "{$GROUPNAME}" only on one node, node1 for example.
After that extension will create aggregate items on node1 and appropriate triggers

**Comment by ddmo** [comment]
Hi, I've created a Zabbix group called "ELASTIC" and I put all my three nodes into but I got this error message: 

No values for key "elasticsearch.cluster_health.active_shards_percent" in group(s) "ELASTIC".

What's wrong?

**Comment by gpavinteractiv** [comment]
> Ok, resolved :)

I get the same thing, How did you solve?
