### ISSUE TITLE
I can't Customize Elasticsearch ip/port, zabbix-server port ?

### ISSUE THREAD

**Issue by y0tsawin** [zarplata/zabbix-agent-extension-elasticsearch#9]
Elasticsearch 
IP 127.0.0.1
Port 2900
I want to config elasticsearch port: 2900, Help me please ?
elasticsearch.stats[{$ZABBIX_SERVER_IP},{$ES_ZBX_PREFIX},ESIP:ESPORT]

![image](https://user-images.githubusercontent.com/43298144/45587905-6cd3ea00-b936-11e8-9a63-0b4a34eb9f94.png)

![image](https://user-images.githubusercontent.com/43298144/45587922-c50aec00-b936-11e8-8b4c-9947e7d607a6.png)

file : /etc/zabbix/zabbix_agentd.d/zabbix-agent-extension-elasticsearch.conf
UserParameter=elasticsearch.stats[*], /usr/bin/zabbix-agent-extension-elasticsearch --zabbix $1 --prefix $2 --user $3 --password $4

**Comment by tears-of-noobs** [comment]
@y0tsawin Hi. Try to use the latest version of the extension. Import the new template and config for zabbix-agent. In the template, you can find new predefined macro {$ES_ADDRESS} you can change it with your values

**Comment by y0tsawin** [comment]
Hi Andrey Platonov,

    Thank you for your support.

Mr. Yotsawin Sopa
System Engineer.
Unixdev Co., Ltd.
Mobile 09-54651739
E-mail : yotsawin@unixdev.co.th <cherawich@unixdev.co.th>

**Comment by y0tsawin** [comment]
Macro {$ES_ADDRESS}  , I can change Address with URL:http://user:user@localhost:2900 ?. I have login Authentication to elasticsearch.

![image](https://user-images.githubusercontent.com/43298144/45877736-0ed95380-bdc9-11e8-933f-21b789d93f9c.png)

**Comment by tears-of-noobs** [comment]
@y0tsawin For authentication there are special macros - `{$ES_USER}` and `{$ES_PASSWORD}`, you should fill these macros with valid username and password of your elasticsearch server (cluster). `{$ES_ADDRESS}` should contain only address with the following format - '127.0.0.1:9200'

**Comment by y0tsawin** [comment]
It' work. Before Config Complete I have to check log error and No Latest Data.

item "rubber-worker1:elasticsearch.indices.stats[{$ZABBIX_SERVER_IP},{$ES_ADDRESS},{$ES_ZBX_PREFIX},{$GROUPNAME},{$ES_USER},{$ES_PASSWORD}]" became not supported: Timeout while executing a shell script.
![image](https://user-images.githubusercontent.com/43298144/45998228-6549d900-c0cc-11e8-897d-1c2e8c042307.png)

![image](https://user-images.githubusercontent.com/43298144/45998292-932f1d80-c0cc-11e8-9827-30b369bc0953.png)
